# Enable Home Assistant API
api:
  encryption:
    # CHANGEME: https://esphome.io/components/api.html
    key: "tWiyI7cNKbY4XxrksezT/2CoAauZOKeQpZn84NPuTlw="

ota:
  - platform: esphome
    password: "1ASD"

substitutions:
  name: "growcube"
  friendly_name: "GrowCube"

wifi:
  ssid: "your wifi ssid"
  password: "your wifi password"

# Enable this if you want to use the files from your local git checkout:
# packages:
#   board: !include packages/elecrow_growcube_esp8266_board.yaml
#   board_debug: !include packages/elecrow_growcube_board_debug.yaml
#   sensor_ads1115: !include packages/sensor_ads1115.yaml
#   sensor_aht20: !include packages/sensor_aht20.yaml
#   sensor_ina219: !include packages/sensor_ina219.yaml
#   time_ds1307: !include packages/time_ds1307.yaml

packages:
  board: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/elecrow_growcube_esp8266_board.yaml
  board_debug: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/elecrow_growcube_board_debug.yaml
  sensor_ads1115: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/sensor_ads1115.yaml
  sensor_aht20: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/sensor_aht20.yaml
  sensor_ina219: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/sensor_ina219.yaml
  time_ds1307: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/time_ds1307.yaml
