# Enable Home Assistant API
api:
  encryption:
    # CHANGEME: https://esphome.io/components/api.html
    key: "tWiyI7cNKbY4XxrksezT/2CoAauZOKeQpZn84NPuTlw="

ota:
  - platform: esphome
    password: "1ASD"

wifi:
  ssid: "your wifi ssid"
  password: "your wifi password"

substitutions:
  name: "growcube"
  friendly_name: "GrowCube"

  # If you want to name the soil moisture sensors more percisely in case the
  # watering channels water multiple plants, rename the entity in your Home
  # Automation Hub.
  channel_A_name: 'Salt'
  channel_B_name: 'Chives'
  channel_C_name: 'Tomatos'
  channel_D_name: 'Pineapple'

  channel_A_run_duration: '4.5min'
  channel_B_run_duration: '5min'
  channel_C_run_duration: '7min'
  channel_D_run_duration: '2min'

  channel_A_soil_below: '45'
  channel_B_soil_below: '45'
  channel_C_soil_below: '40'
  channel_D_soil_below: '80'

  # Calibrate min in dry soil.
  soil_moisture_calibration_A_min: '2.17 -> 0.00'
  # Calibrate max in 100% wet soil.
  soil_moisture_calibration_A_max: '4.96 -> 100.00'

  soil_moisture_calibration_B_min: '2.17 -> 0.00'
  soil_moisture_calibration_B_max: '4.96 -> 100.00'
  soil_moisture_calibration_C_min: '2.17 -> 0.00'
  soil_moisture_calibration_C_max: '4.96 -> 100.00'
  soil_moisture_calibration_D_min: '2.17 -> 0.00'
  soil_moisture_calibration_D_max: '4.96 -> 100.00'

time:
  - id: !extend homeassistant_time
    timezone: "$timezone"
    on_time:
      -
        hours: 21
        minutes: 0
        seconds: 0
        then:
          - script.execute: automated_watering

# Enable this if you want to use the files from your local git checkout:
# packages:
#   board: !include packages/elecrow_growcube_esp8266_board.yaml
#   board_debug: !include packages/elecrow_growcube_board_debug.yaml
#   sensor_ads1115: !include packages/sensor_ads1115.yaml
#   sensor_aht20: !include packages/sensor_aht20.yaml
#   sensor_ina219: !include packages/sensor_ina219.yaml
#   time_ds1307: !include packages/time_ds1307.yaml
#   automated_watering: !include packages/automated_watering.yaml

packages:
  board: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/elecrow_growcube_esp8266_board.yaml
  board_debug: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/elecrow_growcube_board_debug.yaml
  sensor_ads1115: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/sensor_ads1115.yaml
  sensor_aht20: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/sensor_aht20.yaml
  sensor_ina219: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/sensor_ina219.yaml
  time_ds1307: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/time_ds1307.yaml
  automated_watering: github://MakersFunDuck/ESPhome-port-for-GrowCube-Plant-Watering-System-Garden---Smart-Watering-System/packages/automated_watering.yaml
