sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    current:
      name: "Pump Current"
      id: pump_current
      entity_category: diagnostic
    power:
      name: "Pump Power"
      entity_category: diagnostic
    bus_voltage:
      name: "Pump Voltage"
      entity_category: diagnostic
    max_voltage: 32.0V
    max_current: 3.2A
    update_interval: 100ms
