esphome:
  on_boot:
    - priority: 1000
      then:
        # read the RTC time once when the system boots
        ds1307.read_time:

time:
  - platform: ds1307
    id: ds1307_time
    # repeated synchronization is not necessary unless the external RTC
    # is much more accurate than the internal clock
    update_interval: never
  - platform: homeassistant
    id: homeassistant_time
    # instead try to synchronize via network repeatedly ...
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        ds1307.write_time:
