switch:
  - platform: gpio
    id: 'valve_${channel}_internal'
    pin:
      pca9554: pca9554a_device
      number: '${io_expander_pin_number}'
      mode:
        output: true
      inverted: false
    restore_mode: ALWAYS_OFF

  # Switches that can be locked by conditions need to be implemented using a
  # template switch like below.
  # Ref: https://github.com/esphome/esphome/pull/3493
  - platform: template
    name: "Water ${channel} ${channel_name}"
    id: 'water_${channel}_before_safety_checks'
    # entity_category: diagnostic
    icon: mdi:valve
    # or mdi:watering-can
    lambda: |-
      return id(water_${channel}_real).state;
    # optimistic: true
    turn_on_action:
      - if:
          condition:
            - or:
              - and:
                - switch.is_on: strict_mode
                - binary_sensor.is_off: any_pump_problem
                - binary_sensor.is_off: 'soil_moisture_${channel}_disconnected'
              - switch.is_off: strict_mode
          then:
            - switch.turn_on: 'water_${channel}_real'
    turn_off_action:
      - switch.turn_off: 'water_${channel}_real'

  - platform: template
    id: 'water_${channel}_real'
    internal: true
    optimistic: true
    turn_on_action:
      - switch.turn_on: 'valve_${channel}_internal'
    turn_off_action:
      # Prevent "water hammer" effect by ensuring pump had time to turn off
      # before valve gets closed.
      # Duration is just a guess. It was choocen to be long enough so that
      # humans can hear the two clicks and know that the pump was turned off
      # first.
      - delay: 200ms
      - switch.turn_off: 'valve_${channel}_internal'

  - platform: template
    name: "Auto Water ${channel} ${channel_name}"
    id: 'auto_water_${channel}'
    entity_category: config
    icon: mdi:arrow-decision-auto
    optimistic: true
    restore_mode: ALWAYS_ON

sensor:

  - platform: duty_time
    id: water_${channel}_work_time
    name: Water ${channel} ${channel_name} Work Time
    lambda: "return id(water_${channel}_real).state;"
    restore: true

binary_sensor:
  - id: !extend 'any_water_channel_open'
    condition:
      or:
        - switch.is_on: 'water_${channel}_real'
